### ISSUE TITLE
`embroider-optimized` Tests suddenly failing

### ISSUE THREAD

**Issue by evoactivity** [evoactivity/ember-svg-jar#255]
Not sure what is triggering this now but this line

https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/packages/ember-cli-fastboot/vendor/experimental-render-mode-rehydrate.js#L4

causes issues for our embroider-optimized scenario

**Comment by bertdeblock** [comment]
That's because the `embroider-optimized` scenario now enables the `staticEmberSource` flag by default.

Similar issues:
- https://github.com/embroider-build/embroider/issues/1575
- https://github.com/mixonic/ember-cli-deprecation-workflow/issues/156

**Comment by evoactivity** [comment]
Seems recent changes have fixed these scenarios.
