### ISSUE TITLE
Documentation on types, strict mode import

### ISSUE THREAD

**Issue by backspace** [evoactivity/ember-svg-jar#259]
I saw in the [documentation on types](https://github.com/ghedamat/ember-svg-jar/blob/dfc5e775177d8b6fcebbe1a11c6da25d4318cd6a/README.md#typescript-usage) to “add the entries in your app by explicitly importing the types of the helper from this addon”, it took me a bit to figure out that I needed this in `types/ember-svg-jar/helpers/svg-jar.d.ts`:

```
import SvgJar from 'ember-svg-jar/helpers/svg-jar';
import type SvgJarType from 'ember-svg-jar/types';

declare module 'ember-svg-jar/helpers/svg-jar' {
  export default SvgJar as SvgJarType;
}
```

(Is that even correct?)

And regarding strict mode, I floundered a bit before finding that this was the import I needed:

```
import svgJar from 'ember-svg-jar/helpers/svg-jar';
```

I could make a PR if these seem worthy of being in the README.

Thanks for the years of work on this!

**Comment by evoactivity** [comment]
> I could make a PR if these seem worthy of being in the README.

Always happy to take PR's :)
