### ISSUE TITLE
Adding Changesets

### ISSUE THREAD

**Issue by evoactivity** [evoactivity/ember-svg-jar#262]
I'd like to automate releases from this repo using [changesets](https://github.com/changesets/changesets)

@ghedamat I'll need you to add an npm token to the repo, or give me more rights so I can set it all up.

**Comment by ghedamat** [comment]
hey @evoactivity 

thanks for reaching out

I'm actually changing career right now and likely won't have time to maintain this repo in the next coming months..

If you prefer I could even transfer you ownership

it's a great package and it definitely could use some love and me and the last maintainer have not had the time to do it justice 

let me know

and either way if you confirm your npm handle I can give you permission or transfer that too

thank you!

**Comment by evoactivity** [comment]
Hey @ghedamat 

I'm happy to take ownership :)

Same name over at npm (evoactivity) I already have the rights to publish but also happy to take ownership there.

Good luck with your new direction! And thanks for the work you have already put into this addon (and other ember related work).

**Comment by ghedamat** [comment]
aand, npm won't let me transfer ownership lol, the option doesn't show somehow and no-one is marked as admin.. weird

but perhaps those perms are enough for now

**Comment by evoactivity** [comment]
Well that's silly lol. I've renamed my fork, I will probably delete it after ownership transfer is successful.

I think I'm good for the NPM perms, I can publish so I should be able to create a token I can use as well.

**Comment by ghedamat** [comment]
this is getting sad-funny

![image](https://github.com/ghedamat/ember-svg-jar/assets/220183/092519d5-a341-4815-aa50-d33f887cf421)


you might have to delete your fork entirely lol

**Comment by evoactivity** [comment]
Ok, repo deleted! Let's see what other hoops it throws at us 😄

**Comment by evoactivity** [comment]
Looks like that worked!

**Comment by ghedamat** [comment]
congrats!! and big thanks! <3

**Comment by evoactivity** [comment]
Going to use release-plan instead
