### ISSUE TITLE
npm tarball is present in published package

### ISSUE THREAD

**Issue by daniellockyer** [evoactivity/ember-svg-jar#268]
#### Describe the bug

Hey @evoactivity! 👋🏻 

It seems a local version of an npm tarball is present in the latest published package: https://www.npmjs.com/package/ember-svg-jar/v/2.4.9?activeTab=code

`ember-svg-jar-v2.4.7.tgz`

Not a huge deal, but it does inflate the size of the package

#### Expected behavior

I would not expect it to be present 🙂 

#### Possible Solution

Add `*.tgz` to `.npmignore` and re-publish

#### Screenshots

![CleanShot 2024-07-02 at 16 43 22@2x](https://github.com/evoactivity/ember-svg-jar/assets/964245/b2a5f75f-4f6f-477e-bf8e-c80d747e48eb)

**Comment by evoactivity** [comment]
Oops! That shouldn't be there! I assumed this would have been ignored already when I did the last releases.

Thanks for the report. I'll get it taken care of later on tonight.

**Comment by evoactivity** [comment]
I forgot about this 😨 

but I've added release-plan to the repo and just published a new release, tarball is gone and shouldn't happen again the future.

**Comment by daniellockyer** [comment]
Nice, thanks!
